---
# This playbook contains web plays that will run docker-compose.

- name: Copy .env for docker-compose
  copy:
    src: .env
    dest: /home/deploy/cuci_in/Docker/.env

- name: Add traefik.toml config file
  template:
    src: traefik.toml.j2
    dest: /home/deploy/cuci_in/Docker/traefik.toml

- name: Add traefik_dynamic.toml config file
  template:
    src: traefik_dynamic.toml.j2
    dest: /home/deploy/cuci_in/Docker/traefik_dynamic.toml

- name: Add acme.json config file
  copy:
    src: acme.json
    dest: /home/deploy/cuci_in/Docker/acme.json
    owner: deploy
    group: deploy
    mode: '0600'

- name: Copy docker-compose-update script
  copy:
    src: docker-compose-update.sh
    dest: /home/deploy/cuci_in/Docker/docker-compose-update.sh
    owner: deploy
    group: deploy
    mode: '0755'

- name: Cronjob update docker everyday
  cron:
    name: Pull docker image everyday
    minute: "0"
    hour: "0"
    job: "/home/deploy/cuci_in/Docker/docker-compose-update.sh"
